language: ruby
rvm:
  - "2.1.1"
  - "2.0.0"
  - "1.9.3"
  - jruby-19mode # JRuby in 1.9 mode

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile

install: "bundle install"

services:
  - elasticsearch

script: "bundle exec rake spec"
